name: Build Gradle project
on:
  push:
  pull_request:
jobs:
  build-gradle-project:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.0
      - name: Run build with Gradle Wrapper
        run: ./gradlew.bat build
      - name: Copy artifact
        run: cp build/libs/Armageddon-*.*.*.jar obfuscate/input.jar
      - name: Obfuscate names
        run: |
          cd obfuscate
          java -jar grunt.jar
      - name: Download zig
        run: |
          curl -L https://ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.4252+6cee98eb3.zip -o zig.zip
          tar -xf zig.zip
      - name: Run jnic
        run: java -javaagent:jnic-loader.jar -jar jnic.jar output.jar output-jnic.jar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: examplemodartifact
          path: obfuscate/output-jnic.jar